### ISSUE TITLE
Could not get unknown property 'nexusUrl'

### ISSUE THREAD

**Issue by pomirleanu** [CameraForensics/elasticsearch-plugins#1]
I am trying to build an elastic search plugin but i got the following error:

> Could not get unknown property 'nexusUrl' for object of type org.gradle.api.internal.artifacts.repositories.DefaultMavenArtifactRepository.

What is nexus and how can I install it? How can I set nexusUrl variable value?

**Comment by pomirleanu** [comment]
Commenting the repo lines seems to

**Comment by ndtreviv** [comment]
you need to put it in your gradle.properties file (~/.gradle/gradle.properties), or indeed just comment it out if you're not using nexus.
